### PR TITLE
CartStartUp File Updated

### PR DESCRIPTION
**Pull request by sushmakoosukuntla**
CartStartUp and Updated CartEvent to CartEventItem in cart.cs and WebMvc  CartModels

### CODE REVIEW

**Comment by misurac** [comment]
I believe we will also need the identityUrl set up in the Cart Startup.

**Comment by sushmakoosukuntla** [comment]
> I believe we will also need the identityUrl set up in the Cart Startup.

Updated the Branch :)

**Comment by misurac** [comment]
looks good to me, let's merge!

**Comment by misurac** [comment]
I'm getting a few errors for the Jwt, I think we have to add a nuget package or something. Looking into it

**Comment by misurac** [comment]
All good to merge

**Pull request merged**
