### PR TITLE
DataFolder

### PR DESCRIPTION
**Pull request by LalithaNadimpalli**
Datafolder

### CODE REVIEW

**Comment by misurac** [comment]
We just have to remember to change OrdersContext and MigrateDatabase to the final version that Kal went with: https://github.com/KalAcademyNP/JewelsOnContainersSWC9/blob/main/OrderApi/Data/OrdersContext.cs

**Comment by sushmakoosukuntla** [comment]
> We just have to remember to change OrdersContext and MigrateDatabase to the final version that Kal went with: https://github.com/KalAcademyNP/JewelsOnContainersSWC9/blob/main/OrderApi/Data/OrdersContext.cs

Agree!

**Review by mike4741 — COMMENTED** [review]
i don't  think we need OnModelCreatin in ordercontext class

**Comment by LalithaNadimpalli** [comment]
I think we don't have too if we run the migrate command in initial stages but correct me if I am wrong...I don't think we need to make those changes if we run before integrating but we can do the changes if we find any issues

**Comment by LalithaNadimpalli** [comment]
I saw that it's not der in Jewels project but while explaining the class we created it so I added columns but I can delete and submit the PR again

**Comment by LalithaNadimpalli** [comment]
done with the changes

**Comment by misurac** [comment]
We will also need lines 13 and 14 added to OrderItem: https://github.com/KalAcademyNP/JewelsOnContainersSWC9/blob/main/OrderApi/Models/OrderItem.cs

Can be done now or later but maybe best to do it now.

**Review by mike4741 — COMMENTED** [review]
it looks good to me

**Comment by LalithaNadimpalli** [comment]
I see those lines already in models

**Pull request merged**
