### PR TITLE
EventTypeAPI

### PR DESCRIPTION
**Pull request by LalithaNadimpalli**

### CODE REVIEW

**Comment by misurac** [comment]
Do we want to add another route to filter by event type? Suppose we can add that later as well

**Comment by LalithaNadimpalli** [comment]
Just corrected..so no need to add another route

**Review by sushmakoosukuntla — COMMENTED** [review]
I think, you have to write GeteventsByType as well. Instead of pushing small chunks of your part, complete the whole part and push. :)

**Comment by LalithaNadimpalli** [comment]
For EventTypes only I have written and that is only small part to finish so I pushed it..If you remember what Kal has done for Brand and type the same we can add this and in UI we can able to filter as we did for Jewels project

**Pull request closed without merging**
